from . import ir_model_fields
from . import ai_agent
from . import ai_agent_inherit
from . import discuss_channel
from . import res_partner
from . import ai_composer
from . import ai_prompt_button
from . import res_config_settings
from . import ai_providers
from . import ai_agent_source
from . import ai_embedding
from . import ir_attachment
from . import models
from . import ir_actions_server
from . import ai_topic
from . import mail_thread
